services:
  - type: web
    name: ai-property-search
    env: python
    region: oregon
    branch: main
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "streamlit run main.py --server.port $PORT --server.address 0.0.0.0"
    autoDeploy: true
